"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { motion } from "framer-motion";
import { Activity, AlertTriangle, ArrowUpRight, Building2, CalendarDays, CheckCircle2, FileUp, Hospital, MapPin, RefreshCw, Search, ShieldCheck, Stethoscope, TrendingUp } from "lucide-react";
import { api, type HospitalAppointment, type PatientProfile } from "../../../lib/api";

type Forecast = { date: string; day: string; icu_demand: number; general_demand: number; opd_patients: number; doctor_demand: number; demand_score: number; status: string };
type Analysis = { current: { icu_occupancy_percent: number; icu_available_beds: number; general_occupancy_percent: number; general_available_beds: number; overall_demand_score: number; status: string }; forecast: Forecast[]; peak: Forecast; shortage_risk: boolean; nearby_support_candidates: { name: string; distance_km: number; available_icu_beds: number; available_general_beds: number; status: string }[]; recommended_actions: string[]; model: { name: string; history_observations_used: number; method: string }; disclaimer: string };

const history = [{ icu_occupied: 249, general_occupied: 1120, opd_patients: 360, emergency_patients: 126 }, { icu_occupied: 255, general_occupied: 1140, opd_patients: 372, emergency_patients: 130 }, { icu_occupied: 260, general_occupied: 1158, opd_patients: 381, emergency_patients: 136 }, { icu_occupied: 268, general_occupied: 1176, opd_patients: 390, emergency_patients: 142 }];
const statusStyle = (s: string) => s === "critical" ? "bg-rose-50 text-rose-700 border-rose-100" : s === "high" ? "bg-amber-50 text-amber-700 border-amber-100" : s === "moderate" ? "bg-yellow-50 text-yellow-700 border-yellow-100" : "bg-emerald-50 text-emerald-700 border-emerald-100";
const barStyle = (s: string) => s === "critical" ? "bg-rose-500" : s === "high" ? "bg-amber-500" : s === "moderate" ? "bg-yellow-500" : "bg-emerald-500";
const title = (s: string) => s.charAt(0).toUpperCase() + s.slice(1);

export default function HospitalDashboardPage() {
  const [form, setForm] = useState({ icuTotal: 300, icuOccupied: 280, wardTotal: 1500, wardOccupied: 1200, opd: 400, emergency: 150, doctors: 85 });
  const [analysis, setAnalysis] = useState<Analysis | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [patientId, setPatientId] = useState("1002");
  const [appointmentPatient, setAppointmentPatient] = useState<PatientProfile | null>(null);
  const [appointments, setAppointments] = useState<HospitalAppointment[]>([]);
  const [appointmentLoading, setAppointmentLoading] = useState(false);
  const [appointmentError, setAppointmentError] = useState("");
  const [reportFile, setReportFile] = useState<File | null>(null);
  const [reportTitle, setReportTitle] = useState("");
  const [reportType, setReportType] = useState("Blood");
  const [reportSummary, setReportSummary] = useState("");
  const [reportUploading, setReportUploading] = useState(false);
  const [reportMessage, setReportMessage] = useState("");
  const [hospitalAppointments, setHospitalAppointments] = useState<HospitalAppointment[]>([]);
  const [queueLoading, setQueueLoading] = useState(true);
  const [queueError, setQueueError] = useState("");
  const icuPercent = useMemo(() => Math.round((form.icuOccupied / form.icuTotal) * 1000) / 10, [form]);
  const wardPercent = useMemo(() => Math.round((form.wardOccupied / form.wardTotal) * 1000) / 10, [form]);
  const set = (key: keyof typeof form, value: string) => setForm((p) => ({ ...p, [key]: Math.max(0, Number(value) || 0) }));
  const loadAppointmentQueue = async () => { try { setQueueError(""); setHospitalAppointments((await api.getHospitalAppointments()).appointments); } catch (err) { setQueueError(err instanceof Error ? err.message : "Could not load appointment requests."); } finally { setQueueLoading(false); } };
  useEffect(() => { loadAppointmentQueue(); }, []);
  const changeAppointmentStatus = async (appointment: HospitalAppointment, status: "confirmed" | "completed" | "cancelled") => { try { await api.updateHospitalAppointment(appointment._id, status); await loadAppointmentQueue(); if (appointmentPatient) await findPatientAppointment(); } catch (err) { setQueueError(err instanceof Error ? err.message : "Could not update the appointment."); } };

  async function analyse() {
    if (!form.icuTotal || !form.wardTotal || !form.doctors || form.icuOccupied > form.icuTotal || form.wardOccupied > form.wardTotal) { setError("Enter valid capacity values. Occupied beds cannot exceed total beds."); return; }
    setLoading(true); setError("");
    try {
      const res = await fetch("/api/capacity", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ icu: { total_beds: form.icuTotal, occupied_beds: form.icuOccupied }, general_ward: { total_beds: form.wardTotal, occupied_beds: form.wardOccupied }, opd_patients: form.opd, emergency_patients: form.emergency, doctors_available: form.doctors, history, nearby_hospitals: [{ name: "Green Valley Medical Centre", distance_km: 4.8, icu_total: 120, icu_occupied: 62, general_total: 500, general_occupied: 275 }, { name: "Riverside Hospital", distance_km: 7.2, icu_total: 90, icu_occupied: 76, general_total: 380, general_occupied: 320 }, { name: "Metro Care Hospital", distance_km: 9.6, icu_total: 160, icu_occupied: 101, general_total: 700, general_occupied: 410 }] }) });
      const data = await res.json(); if (!res.ok) throw new Error(data.error || "Unable to analyse capacity."); setAnalysis(data as Analysis);
    } catch (e) { setError(e instanceof Error ? e.message : "Unable to analyse capacity."); } finally { setLoading(false); }
  }

  async function findPatientAppointment() {
    if (!patientId.trim()) return;
    setAppointmentLoading(true); setAppointmentError(""); setAppointmentPatient(null);
    try {
      const result = await api.getHospitalPatientAppointments(patientId.trim());
      setAppointmentPatient(result.patient); setAppointments(result.appointments);
    } catch (e) { setAppointmentError(e instanceof Error ? e.message : "Unable to find the patient appointment."); }
    finally { setAppointmentLoading(false); }
  }

  async function uploadReport() {
    if (!appointmentPatient || !reportFile || !reportTitle.trim()) { setReportMessage("Choose a report file and enter a title."); return; }
    setReportUploading(true); setReportMessage("");
    try {
      await api.uploadHospitalPatientReport(appointmentPatient.custom_id, reportFile, { title: reportTitle.trim(), type: reportType, summary: reportSummary.trim() || undefined });
      setReportMessage("Report uploaded. It is now visible in the patient history.");
      setReportFile(null); setReportTitle(""); setReportSummary("");
    } catch (e) { setReportMessage(e instanceof Error ? e.message : "Could not upload the report."); }
    finally { setReportUploading(false); }
  }


  return <main className="min-h-screen bg-[#f5f7f6] text-[#17201d]">
    <header className="sticky top-0 z-20 flex items-center justify-between border-b border-black/[.06] bg-[#f9fbfa]/90 px-5 py-4 backdrop-blur-xl sm:px-10"><Link href="/" className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#17201d] text-white"><Activity size={17}/></span><span><b className="block text-sm tracking-[-.02em]">VITAWEAVE</b><small className="text-[8px] font-medium uppercase tracking-[.2em] text-black/40">Hospital intelligence</small></span></Link><div className="flex items-center gap-2 text-[10px] font-medium uppercase tracking-[.13em] text-black/45"><span className="h-2 w-2 rounded-full bg-emerald-500"/>Operations online <Building2 size={15}/><span className="hidden sm:inline">City General Hospital</span></div></header>
    <div className="mx-auto max-w-[1440px] px-5 py-7 sm:px-10">
      <section className="relative overflow-hidden rounded-[28px] border border-black/[.06] bg-[#e9eff2] p-6 sm:p-9"><div className="absolute -right-24 -top-28 h-80 w-80 rounded-full bg-blue-200/40 blur-3xl"/><div className="relative grid gap-8 lg:grid-cols-[1.35fr_.65fr] lg:items-end"><div><p className="mb-4 flex items-center gap-2 font-mono text-[10px] uppercase tracking-[.18em] text-[#54749a]"><span className="h-1.5 w-1.5 rounded-full bg-[#54749a]"/>Adaptive demand intelligence</p><h1 className="max-w-3xl text-[clamp(2.7rem,6vw,5.7rem)] font-medium leading-[.87] tracking-[-.07em]">See pressure early.<br/><span className="text-black/35">Plan capacity with confidence.</span></h1><p className="mt-6 max-w-2xl text-sm leading-6 text-black/55">Enter today&apos;s operational data. The model combines it with synthetic hospital patterns and recent observations to forecast the next seven days—not simply repeat today&apos;s numbers.</p></div><div className="rounded-2xl border border-white/60 bg-white/65 p-5 shadow-[0_18px_50px_rgba(34,59,75,.08)] backdrop-blur"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#17201d] text-white"><TrendingUp size={18}/></span><div><p className="text-xs font-semibold">Forecast model ready</p><p className="mt-1 text-[10px] text-black/45">Seasonality · weekday load · trend calibration</p></div></div><button onClick={analyse} disabled={loading} className="mt-5 flex h-11 w-full items-center justify-center gap-2 rounded-xl bg-[#17201d] text-xs font-medium text-white transition hover:bg-[#2c3b36] disabled:opacity-60">{loading ? <RefreshCw size={14} className="animate-spin"/> : <ArrowUpRight size={14}/>} {loading ? "Analysing demand…" : "Run 7-day capacity analysis"}</button></div></div></section>
      <section className="mt-5 rounded-[23px] border border-black/[.06] bg-white p-6 shadow-[0_8px_30px_rgba(20,30,25,.025)]"><div className="flex items-end justify-between gap-4"><div><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-black/45">Appointment requests</p><h2 className="mt-1 text-xl font-medium tracking-[-.04em]">Live hospital queue</h2></div><button onClick={loadAppointmentQueue} className="flex h-9 items-center gap-2 rounded-lg border border-black/[.1] px-3 text-xs"><RefreshCw size={13} className={queueLoading ? "animate-spin" : ""}/>Refresh</button></div>{queueError && <p className="mt-3 rounded-lg bg-rose-50 p-3 text-xs text-rose-700">{queueError}</p>}<div className="mt-4 space-y-2">{!queueLoading && !hospitalAppointments.length && <p className="rounded-xl bg-[#f8faf9] p-4 text-sm text-black/45">No appointment requests yet.</p>}{hospitalAppointments.map((appointment) => <div key={appointment._id} className="flex flex-wrap items-center gap-3 rounded-xl bg-[#f8faf9] p-3"><div className="min-w-[170px] flex-1"><p className="text-sm font-semibold">{appointment.patient?.full_name || "Patient"} <span className="font-mono text-[10px] text-black/45">{appointment.patient?.custom_id}</span></p><p className="mt-1 text-xs text-black/55">{appointment.department} · {new Intl.DateTimeFormat("en-IN", { dateStyle: "medium", timeStyle: "short" }).format(new Date(appointment.scheduled_for))}</p><p className="mt-1 text-[11px] text-black/45">{appointment.doctor ? `Preferred: ${appointment.doctor.full_name}` : "No doctor preference"}{appointment.reason ? ` · ${appointment.reason}` : ""}</p></div><span className="rounded-full bg-white px-2 py-1 text-[9px] font-bold uppercase text-[#52786d]">{appointment.status}</span>{appointment.status === "requested" && <><button onClick={() => changeAppointmentStatus(appointment, "confirmed")} className="h-8 rounded-lg bg-[#17201d] px-3 text-[10px] font-medium text-white">Confirm</button><button onClick={() => changeAppointmentStatus(appointment, "cancelled")} className="h-8 rounded-lg border border-rose-100 px-3 text-[10px] text-rose-700">Decline</button></>}{appointment.status === "confirmed" && <button onClick={() => changeAppointmentStatus(appointment, "completed")} className="h-8 rounded-lg border border-[#b9c9c2] px-3 text-[10px] text-[#52786d]">Mark completed</button>}</div>)}</div></section>
      <section className="mt-5 rounded-[23px] border border-black/[.06] bg-white p-6 shadow-[0_8px_30px_rgba(20,30,25,.025)]"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-black/45">Patient appointment history</p><h2 className="mt-1 text-xl font-medium tracking-[-.04em]">Find a booked patient</h2><p className="mt-1 text-xs text-black/45">Use the patient ID to view appointments at this hospital.</p></div><div className="flex w-full gap-2 sm:w-auto"><input value={patientId} onChange={(e) => setPatientId(e.target.value)} onKeyDown={(e) => e.key === "Enter" && findPatientAppointment()} placeholder="1002 or PAT-1002" className="h-11 min-w-0 flex-1 rounded-xl border border-black/[.1] bg-[#fbfcfb] px-3 text-sm outline-none focus:border-[#54749a] sm:w-48"/><button onClick={findPatientAppointment} disabled={appointmentLoading} className="flex h-11 items-center gap-2 rounded-xl bg-[#17201d] px-4 text-xs font-medium text-white disabled:opacity-60"><Search size={14}/>{appointmentLoading ? "Searching…" : "Find patient"}</button></div></div>
        {appointmentError && <p className="mt-4 rounded-xl bg-rose-50 px-4 py-3 text-sm text-rose-700">{appointmentError}</p>}
        {appointmentPatient && <div className="mt-5 grid gap-4 lg:grid-cols-[1fr_1.2fr]"><div className="rounded-2xl bg-[#f4f8f6] p-5"><div className="flex items-start justify-between"><div><p className="text-lg font-semibold">{appointmentPatient.full_name}</p><p className="mt-1 font-mono text-xs text-[#52786d]">{appointmentPatient.custom_id}</p></div><span className="rounded-full bg-white px-2.5 py-1 text-[10px] font-semibold text-[#52786d]">{appointmentPatient.blood_type || "Blood type unavailable"}</span></div><div className="mt-5 grid grid-cols-2 gap-3 text-xs"><Info label="Phone" value={appointmentPatient.contact_phone || "—"}/><Info label="DOB" value={appointmentPatient.dob || "—"}/><Info label="Allergies" value={appointmentPatient.known_allergies.join(", ") || "None recorded"}/><Info label="Conditions" value={appointmentPatient.chronic_conditions.join(", ") || "None recorded"}/></div></div><div className="rounded-2xl border border-black/[.06] p-5"><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-black/45">Appointments at City General</p><div className="mt-3 space-y-3">{appointments.map((appointment) => <div key={appointment._id} className="flex gap-3 rounded-xl bg-[#fbfcfb] p-3"><CalendarDays className="mt-0.5 shrink-0 text-[#54749a]" size={17}/><div><p className="text-sm font-semibold">{appointment.department}</p><p className="mt-0.5 text-xs text-black/50">{new Intl.DateTimeFormat("en-IN", { dateStyle: "medium", timeStyle: "short" }).format(new Date(appointment.scheduled_for))}</p><p className="mt-1 text-xs text-black/60">{appointment.reason || "No reason supplied"}</p></div><span className="ml-auto h-fit rounded-full bg-emerald-50 px-2 py-1 text-[9px] font-bold uppercase text-emerald-700">{appointment.status}</span></div>)}</div></div></div>}
        {appointmentPatient && <div className="mt-4 rounded-2xl border border-dashed border-[#b9c9c2] bg-[#f8fbf9] p-5"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#e5f0eb] text-[#52786d]"><FileUp size={17}/></span><div><p className="text-sm font-semibold">Upload a report to {appointmentPatient.full_name}&apos;s history</p><p className="text-xs text-black/45">This report will be added to the patient&apos;s clinical timeline.</p></div></div><div className="mt-4 grid gap-3 md:grid-cols-4"><input type="file" accept=".pdf,.doc,.docx,.jpg,.jpeg,.png" onChange={(e) => setReportFile(e.target.files?.[0] || null)} className="text-xs md:col-span-2"/><input value={reportTitle} onChange={(e) => setReportTitle(e.target.value)} placeholder="Report title" className="h-10 rounded-xl border border-black/[.1] bg-white px-3 text-sm outline-none"/><select value={reportType} onChange={(e) => setReportType(e.target.value)} className="h-10 rounded-xl border border-black/[.1] bg-white px-3 text-sm"><option>Blood</option><option>ECG</option><option>MRI</option><option>CT</option><option>X-Ray</option><option>Prescription</option><option>Other</option></select></div><textarea value={reportSummary} onChange={(e) => setReportSummary(e.target.value)} placeholder="Optional clinical summary" rows={2} className="mt-3 w-full rounded-xl border border-black/[.1] bg-white p-3 text-sm outline-none"/><div className="mt-3 flex items-center gap-3"><button onClick={uploadReport} disabled={reportUploading} className="flex h-10 items-center gap-2 rounded-xl bg-[#17201d] px-4 text-xs font-medium text-white disabled:opacity-60"><FileUp size={14}/>{reportUploading ? "Uploading…" : "Upload report"}</button>{reportMessage && <p className="text-xs text-[#52786d]">{reportMessage}</p>}</div></div>}
      </section>
      <div className="mt-5 grid gap-5 xl:grid-cols-[.88fr_1.12fr]">
        <section className="rounded-[23px] border border-black/[.06] bg-white p-6 shadow-[0_8px_30px_rgba(20,30,25,.025)]"><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-black/45">Daily operational input</p><h2 className="mt-1 text-xl font-medium tracking-[-.04em]">Today&apos;s capacity snapshot</h2><div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4">{[["ICU total beds","icuTotal"],["ICU occupied","icuOccupied"],["Ward total beds","wardTotal"],["Ward occupied","wardOccupied"],["OPD patients","opd"],["Emergency patients","emergency"],["Doctors available","doctors"]].map(([label,key]) => <label key={key} className="block"><span className="mb-1.5 block text-[9px] font-medium uppercase tracking-[.1em] text-black/40">{label}</span><input type="number" min="0" value={form[key as keyof typeof form]} onChange={(e) => set(key as keyof typeof form, e.target.value)} className="h-10 w-full rounded-lg border border-black/[.09] bg-[#fbfcfb] px-3 text-sm outline-none focus:border-[#54749a] focus:ring-2 focus:ring-[#54749a]/10"/></label>)}</div><div className="mt-5 grid grid-cols-2 gap-3"><Mini label="ICU live occupancy" value={`${icuPercent}%`} detail={`${form.icuTotal-form.icuOccupied} beds available`}/><Mini label="Ward live occupancy" value={`${wardPercent}%`} detail={`${form.wardTotal-form.wardOccupied} beds available`}/></div>{error && <p className="mt-4 rounded-lg bg-rose-50 px-3 py-2 text-xs text-rose-700">{error}</p>}</section>
        <section className="rounded-[23px] border border-black/[.06] bg-[#17201d] p-6 text-white"><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-white/45">Decision summary</p><h2 className="mt-1 text-xl font-medium tracking-[-.04em]">What the model sees next</h2>{analysis ? <><div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4"><Mini dark label="ICU beds now" value={`${analysis.current.icu_available_beds}`}/><Mini dark label="Peak ICU demand" value={`${analysis.peak.icu_demand}`}/><Mini dark label="Doctors needed" value={`${analysis.peak.doctor_demand}`}/><Mini dark label="Expected peak" value={analysis.peak.day}/></div><div className="mt-5 rounded-xl border border-white/10 bg-white/[.07] p-4 text-xs leading-5 text-white/75">{analysis.shortage_risk ? "Capacity shortage risk identified during the forecast window." : "No bed-capacity breach predicted in the forecast window."} <span className="text-white/45">Peak demand score: {analysis.peak.demand_score}/100.</span></div></> : <div className="mt-8 rounded-xl border border-dashed border-white/15 p-6 text-center"><TrendingUp className="mx-auto text-white/35" size={24}/><p className="mt-3 text-sm text-white/70">Run the analysis to see the seven-day forecast.</p><p className="mt-1 text-[10px] text-white/40">Uses a synthetic baseline calibrated by recent observations.</p></div>}</section>
      </div>
      {analysis && <motion.div initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} className="mt-5 grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><section className="rounded-[23px] border border-black/[.06] bg-white p-6"><div className="flex items-center justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-black/45">7-day demand forecast</p><h2 className="mt-1 text-xl font-medium tracking-[-.04em]">Demand trajectory</h2></div><span className={`rounded-full border px-2.5 py-1 text-[9px] font-bold uppercase tracking-[.12em] ${statusStyle(analysis.peak.status)}`}>Peak {title(analysis.peak.status)}</span></div><div className="mt-6 space-y-3">{analysis.forecast.map((item) => <div key={item.date} className="grid grid-cols-[42px_1fr_45px] items-center gap-3"><span className="text-xs font-medium">{item.day}</span><div><div className="h-2 rounded-full bg-black/[.06]"><div className={`h-2 rounded-full ${barStyle(item.status)}`} style={{width:`${Math.min(item.demand_score,100)}%`}}/></div><p className="mt-1 text-[10px] text-black/43">ICU {item.icu_demand} · Ward {item.general_demand} · OPD {item.opd_patients} · {item.doctor_demand} doctors</p></div><span className="text-right text-xs font-medium">{item.demand_score}%</span></div>)}</div></section><section className="rounded-[23px] border border-black/[.06] bg-white p-6"><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-black/45">Recommended actions</p><h2 className="mt-1 text-xl font-medium tracking-[-.04em]">Act before the peak</h2><div className="mt-5 space-y-3">{analysis.recommended_actions.map((action) => <div key={action} className="flex gap-3 rounded-xl bg-[#f8faf9] p-3.5"><CheckCircle2 size={16} className="mt-0.5 shrink-0 text-[#608d82]"/><p className="text-xs leading-5 text-black/62">{action}</p></div>)}</div><p className="mt-4 text-[10px] leading-4 text-black/38">{analysis.disclaimer}</p></section></motion.div>}
      {analysis && <section className="mt-5 rounded-[23px] border border-black/[.06] bg-white p-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-black/45">Regional capacity network</p><h2 className="mt-1 text-xl font-medium tracking-[-.04em]">Nearby lower-demand support options</h2></div><p className="flex items-center gap-1.5 text-[10px] text-black/40"><MapPin size={13}/>Within 10 km</p></div>{analysis.nearby_support_candidates.length ? <div className="mt-5 grid gap-3 md:grid-cols-3">{analysis.nearby_support_candidates.map((h) => <div key={h.name} className="rounded-xl border border-black/[.06] bg-[#fbfcfb] p-4"><div className="flex items-start justify-between"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-[#edf3f1] text-[#4c756c]"><Hospital size={15}/></span><span className={`rounded-full border px-2 py-0.5 text-[8px] font-bold uppercase ${statusStyle(h.status)}`}>{title(h.status)}</span></div><p className="mt-4 text-sm font-semibold">{h.name}</p><p className="mt-1 text-[10px] text-black/45">{h.distance_km.toFixed(1)} km away</p><div className="mt-4 grid grid-cols-2 gap-2 border-t border-black/[.06] pt-3 text-[10px]"><span><b className="block text-base">{h.available_icu_beds}</b>ICU beds</span><span><b className="block text-base">{h.available_general_beds}</b>ward beds</span></div></div>)}</div> : <p className="mt-5 rounded-xl bg-[#f8faf9] p-4 text-sm text-black/50">No lower-demand support options were identified within 10 km.</p>}<p className="mt-4 flex items-start gap-2 text-[10px] leading-4 text-black/40"><AlertTriangle size={13} className="mt-0.5 shrink-0"/>Recommendations identify coordination candidates only. Authorised hospital teams must confirm capacity and patient suitability before any transfer.</p></section>}
      <footer className="mt-8 flex flex-col gap-3 border-t border-black/[.06] py-5 text-[9px] uppercase tracking-[.14em] text-black/30 sm:flex-row sm:justify-between"><span className="flex items-center gap-2"><ShieldCheck size={13}/>Clinical operations decision support</span><span className="flex items-center gap-2"><Stethoscope size={13}/>Synthetic-adaptive forecasting</span></footer>
    </div></main>;
}
function Mini({label,value,detail,dark=false}:{label:string;value:string;detail?:string;dark?:boolean}) { return <div className={dark ? "rounded-xl border border-white/10 bg-white/[.07] p-3" : "rounded-xl bg-[#f8faf9] p-4"}><p className={dark ? "text-xl font-medium tracking-[-.05em]" : "text-2xl font-medium tracking-[-.06em]"}>{value}</p><p className={dark ? "mt-1 text-[9px] uppercase tracking-[.1em] text-white/45" : "mt-1 text-[9px] uppercase tracking-[.12em] text-black/40"}>{label}</p>{detail && <p className="mt-1 text-[10px] text-black/45">{detail}</p>}</div>; }
function Info({label,value}:{label:string;value:string}) { return <div><p className="text-[9px] font-semibold uppercase tracking-[.12em] text-black/40">{label}</p><p className="mt-1 leading-5 text-black/70">{value}</p></div>; }
